test_with_go_modules: &test_with_go_modules
  steps:
  - checkout
  - run: go test ./...
  - run: go vet ./...
  - run: go build
  - run: ls -lah
  - run: mkdir docker_dir
  - run: cp Dockerfile docker_dir/Dockerfile
  - run: cp daptin docker_dir/main
  - run: cd docker_dir
  - setup_remote_docker:
      docker_layer_caching: true
  - run: docker build -t daptin/daptin:circleci .
  - run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  - run: docker push daptin/daptin:circleci
  - store_artifacts:
      path: /go/src/github.com/daptin/daptin/main
      destination: daptin

test_without_go_modules: &test_without_go_modules
  working_directory: /go/src/github.com/daptin/daptin
  steps:
  - checkout
  - run: go get -v -t -d ./...
  - run: go test ./...
  - run: go vet ./...
  - run: go build
  - store_artifacts:
      path: /go/src/github.com/daptin/daptin/main
      destination: daptin

defaults: &defaults
  <<: *test_with_go_modules

version: 2
jobs:
  golang:latest:
    <<: *defaults
    docker:
    - image: circleci/golang:latest
  coveralls:
    steps:
    - checkout
    - run: go get github.com/daptin/daptin
    - run: go test ./... -coverpkg github.com/daptin/daptin/... -v -cover -coverprofile=coverage.out
    - run: go get github.com/mattn/goveralls
    - run: /go/bin/goveralls -coverprofile=coverage.out -service=circle-ci -repotoken $GOVERTOKEN
    docker:
    - image: circleci/golang:latest
workflows:
  version: 2
  build:
    jobs:
    - golang:latest
    - coveralls