site_name: Daptin
site_favicon: images/favicon.png
site_url: https://daptin.github.io/daptin/
pages:
- Overview: index.md
- Download and Deploy: setting-up/installation.md
- Accessing the web dashboard: setting-up/settingup.md
- User management:
    - New User: user-management/new-users.md
    - Sign in API: user-management/signin.md
    - Access control: user-management/new-users.md
- Data model: setting-up/data_modeling.md
- HTTP JSON API:
  - CRUD API: apis/crud/#crud-api
  - Action API: apis/crud/#action-api
  - Relation API: apis/crud/#relation-apis
  - Aggregation API: apis/crud/#aggregate-api
  - State machine API: apis/crud/#state-machine-apis
  - Metadata API: apis/crud/#metadata-api
- Actions:
  - What are actions: actions/actions.md
  - Actions list: actions/default_actions.md
  - OutComes: actions/outcomes.md
  - Examples: actions/examples.md
- GraphQL: features/enable-graphql.md
- Data Auditing: features/enable-data-auditing.md
- Multilingual Table: features/enable-multilingual-table.md
- SMTP/IMPS server: features/enable-smtp-imap.md
- State tracking: state/machines.md
- OAuth:
  - OAuth Connections: extend/oauth_connection.md
  - OAuth Tokens: extend/oauth_token.md
- 3rd party API Integrations: integrations/overview.md
- Cloud store: cloudstore/cloudstore.md
- Cloud store backed asset columns: cloudstore/assetcolumns.md
- Sub-sites:
  - Creating a subsite: subsite/subsite.md
  - Live editing a subsite: subsite/grapes.md
  - Basic Authentication: subsite/basic_auth.md
- Internal Reference Documents:
  - Data store format: data-modeling/data_storage.md
  - Data exchange and sync: extend/data_exchange.md
  - Data streams: streams/streams.md
- Global Configuration: setting-up/configuration.md
theme:
  name: material
  logo: images/theme-logo.png
  favicon: images/theme-favicon.png
extra_css:
- css/theme_extra.css
google_analytics: ['UA-114227400-1', 'docs.dapt.in']
extra:
  disqus: daptin-documentation
markdown_extensions:
- toc:
    permalink: Link
- admonition
- codehilite
- pymdownx.superfences
- pymdownx.tasklist
- pymdownx.magiclink