---
# Github Actions build for daptin
# -*- compile-command: "yamllint -f parsable build.yml" -*-

name: build

# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:

jobs:
  build:
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        job_name: ['linux', 'mac', 'windows_amd64', 'other_os', 'modules_race']

        include:
          - job_name: linux
            os: ubuntu-latest
            go: '1.14.x'
            modules: 'on'
            gotags: cmount
            build_flags: '-include "^linux/"'
            check: true
            quicktest: true
            deploy: true

          - job_name: mac
            os: macOS-latest
            go: '1.14.x'
            modules: 'on'
            gotags: ''  # cmount doesn't work on osx travis for some reason
            build_flags: '-include "^darwin/amd64" -cgo'
            quicktest: true
            deploy: true

          - job_name: windows_amd64
            os: windows-latest
            go: '1.14.x'
            modules: 'on'
            gotags: cmount
            build_flags: '-include "^windows/amd64" -cgo'
            deploy: true

          - job_name: other_os
            os: ubuntu-latest
            go: '1.14.x'
            modules: 'on'
            build_flags: "-exclude '^(windows/|darwin/amd64|linux/)'"
            compile_all: true
            deploy: true

          - job_name: modules_race
            os: ubuntu-latest
            go: '1.14.x'
            modules: 'on'
            quicktest: true

    name: ${{ matrix.job_name }}

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1


      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Install node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Set environment variables
        shell: bash
        run: |
          
          echo "GOPATH=${{ runner.workspace }}" >> $GITHUB_ENV
          echo "GO111MODULE=${{ matrix.modules }}" >> $GITHUB_ENV
          echo "GOTAGS=${{ matrix.gotags }}" >> $GITHUB_ENV
          echo "BUILD_FLAGS=${{ matrix.build_flags }}" >> $GITHUB_ENV
          echo "${{ runner.workspace }}/bin" >> $GITHUB_PATH
          
          if [[ "${{ matrix.goarch }}" != "" ]]; then echo "GOARCH=${{ matrix.goarch }}" >> $GITHUB_ENV ; fi
          if [[ "${{ matrix.cgo }}" != "" ]]; then echo "CGO_ENABLED=${{ matrix.cgo }}" >> $GITHUB_ENV  ; fi
      - name: Install Libraries on Linux
        shell: bash
        run: |
          sudo modprobe fuse
          sudo chmod 666 /dev/fuse
          sudo chown root:$USER /etc/fuse.conf
          sudo apt-get install fuse libfuse-dev rpm pkg-config rclone
        if: matrix.os == 'ubuntu-latest'


      - name: Install Libraries on Windows
        shell: powershell
        run: |
          $ProgressPreference = 'SilentlyContinue'
          choco install -y winfsp zip
        if: matrix.os == 'windows-latest'

      - name: Print Go version and environment
        shell: bash
        run: |
          printf "Using go at: $(which go)\n"
          printf "Go version: $(go version)\n"
          printf "\n\nGo environment:\n\n"
          go env
          printf "\n\nDaptin environment:\n\n"
          make vars
          printf "\n\nSystem environment:\n\n"
          env

      - name: Build dashboard
        shell: bash
        run: |
          printf "npm and qusar to build dashboard in ./daptinweb"
          git clone https://github.com/daptin/dadadash daptinweb && cd daptinweb
          npm install -g @quasar/cli
          npm install
          npm run build
          ls -lah dist/spa
          printf "Dashboard build complete"
          cd ..


      - name: Installl gorice on linux
        shell: bash
        run: |
          go get -u -v github.com/ahmetb/govvv
          go get -v github.com/GeertJohan/go.rice
          go get -v github.com/GeertJohan/go.rice/rice
          go install github.com/GeertJohan/go.rice/rice
          $GOPATH/bin/rice embed-go
          ls -lah rice-box.go

        if: matrix.os != 'windows-latest'

      - name: Install gorice on windows
        shell: bash
        run: |
          go get -v github.com/GeertJohan/go.rice
          go get -v github.com/GeertJohan/go.rice/rice
          go install github.com/GeertJohan/go.rice/rice
          $GOPATH\\bin\\rice.exe embed-go
          ls -lah rice-box.go
        if: matrix.os == 'windows-latest' && matrix.goarch != '386'

      - name: Run quick tests
        shell: bash
        run: |
          make
          make quicktest
        if: matrix.quicktest

      - name: Run Race test
        shell: bash
        run: |
          make racequicktest
        if: matrix.racequicktest

      - name: Compile all architectures test
        shell: bash
        run: |
          make
          make compile_all
        if: matrix.compile_all

      - name: Build and deploy built binaries
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then make release_dep ; fi
          ls -lah
          ls -lah daptinweb/dist
          mv daptinweb/dist/spa daptinweb/dist/spa1
          make travis_beta
          ls -lah build/
        if: matrix.deploy && github.head_ref == '' && github.repository == 'daptin/daptin'


      - name: Build and push docker image
        run: |
          go build -o main
          docker build -t daptin/daptin:travis .
          docker login -u="${{ secrets.DOCKER_USERNAME }}" -p="${{ secrets.DOCKER_PASSWORD }}"
          docker push daptin/daptin:travis
        if: matrix.os == 'ubuntu-latest' && matrix.job_name == 'linux'


      - uses: actions/upload-artifact@v1
        continue-on-error: true
        with:
          name: daptin-beta-latest-freebsd-386.zip
          path: build/daptin-beta-latest-freebsd-386.zip
        if: matrix.deploy && github.head_ref == '' && github.repository == 'daptin/daptin'

      - uses: actions/upload-artifact@v1
        continue-on-error: true
        with:
          name: daptin-beta-latest-freebsd-amd64.zip
          path: build/daptin-beta-latest-freebsd-amd64.zip
        if: matrix.deploy && github.head_ref == '' && github.repository == 'daptin/daptin'

      - uses: actions/upload-artifact@v1
        continue-on-error: true
        with:
          name: daptin-beta-latest-freebsd-arm.zip
          path: build/daptin-beta-latest-freebsd-arm.zip
        if: matrix.deploy && github.head_ref == '' && github.repository == 'daptin/daptin'

      - uses: actions/upload-artifact@v1
        continue-on-error: true
        with:
          name: daptin-beta-latest-windows-amd64.zip
          path: build/daptin-beta-latest-windows-amd64.zip
        if: matrix.deploy && github.head_ref == '' && github.repository == 'daptin/daptin'

      - uses: actions/upload-artifact@v1
        continue-on-error: true
        with:
          name: daptin-beta-latest-netbsd-386.zip
          path: build/daptin-beta-latest-netbsd-386.zip
        if: matrix.deploy && github.head_ref == '' && github.repository == 'daptin/daptin'

      - uses: actions/upload-artifact@v1
        continue-on-error: true
        with:
          name: daptin-beta-latest-netbsd-amd64.zip
          path: build/daptin-beta-latest-netbsd-amd64.zip
        if: matrix.deploy && github.head_ref == '' && github.repository == 'daptin/daptin'

      - uses: actions/upload-artifact@v1
        continue-on-error: true
        with:
          name: daptin-beta-latest-netbsd-arm.zip
          path: build/daptin-beta-latest-netbsd-arm.zip
        if: matrix.deploy && github.head_ref == '' && github.repository == 'daptin/daptin'

      - uses: actions/upload-artifact@v1
        continue-on-error: true
        with:
          name: daptin-beta-latest-openbsd-386.zip
          path: build/daptin-beta-latest-openbsd-386.zip
        if: matrix.deploy && github.head_ref == '' && github.repository == 'daptin/daptin'

      - uses: actions/upload-artifact@v1
        continue-on-error: true
        with:
          name: daptin-beta-latest-openbsd-amd64.zip
          path: build/daptin-beta-latest-openbsd-amd64.zip
        if: matrix.deploy && github.head_ref == '' && github.repository == 'daptin/daptin'

      - uses: actions/upload-artifact@v1
        continue-on-error: true
        with:
          name: daptin-beta-latest-osx-386.zip
          path: build/daptin-beta-latest-osx-386.zip
        if: matrix.deploy && github.head_ref == '' && github.repository == 'daptin/daptin'

      - uses: actions/upload-artifact@v1
        continue-on-error: true
        with:
          name: daptin-beta-latest-osx-amd64.zip
          path: build/daptin-beta-latest-osx-amd64.zip
        if: matrix.deploy && github.head_ref == '' && github.repository == 'daptin/daptin'

      - uses: actions/upload-artifact@v1
        continue-on-error: true
        with:
          name: daptin-beta-latest-solaris-amd64.zip
          path: build/daptin-beta-latest-solaris-amd64.zip
        if: matrix.deploy && github.head_ref == '' && github.repository == 'daptin/daptin'


  xgo:
    timeout-minutes: 60
    name: "xgo cross compile"
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v1


      - name: Print env variable
        shell: bash
        id: tagInfo
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}


      - name: Set environment variables
        shell: bash
        run: |
          echo "GOPATH=${{ runner.workspace }}" >> $GITHUB_ENV
          echo "${{ runner.workspace }}/bin" >> $GITHUB_PATH


      - name: Copy Code
        shell: bash
        run: go get github.com/daptin/daptin


      - name: Build dashboard
        shell: bash
        run: |
          printf "npm and qusar to build dashboard in ./daptinweb"
          git clone https://github.com/daptin/dadadash daptinweb && cd daptinweb
          npm install @quasar/cli
          npm install
          npm run build
          ls -lah dist/spa
          printf "Dashboard build complete"
          cd ..


      - name: Installl gorice on linux
        shell: bash
        run: |
          go get -u -v github.com/ahmetb/govvv
          go get -v github.com/GeertJohan/go.rice
          go get -v github.com/GeertJohan/go.rice/rice
          go install github.com/GeertJohan/go.rice/rice
          $GOPATH/bin/rice embed-go
          ls -lah rice-box.go


      - name: Cross-compile daptin
        run: |
          export GO111MODULE=on
          docker pull artpar/daptin-xgo:1.14
          go get -v github.com/karalabe/xgo
          go get
          cd ..
          cp -Rf /home/runner/work/daptin/daptin /home/runner/work/daptin/src
          ls -lah /home/runner/work/daptin
          cd -
          pwd
          go env
          ls -lah
          xgo \
              -image=artpar/daptin-xgo:1.14 \
              -targets=linux/386,darwin/amd64,linux/amd64,linux/arm-5,linux/arm-6,linux/arm-7,linux/mips,linux/mips64,linux/mips64le,linux/mipsle,windows/386,windows/amd64 \
              --tags netgo -ldflags='-linkmode external' -dest build /home/runner/work/daptin/daptin


      - name: Set environment variables
        shell: bash
        run: |
          ls build
          file build/*

      - uses: actions/upload-artifact@v1
        with:
          name: daptin-linux-amd64
          path: build/daptin-linux-amd64
        if: github.head_ref == '' && github.repository == 'daptin/daptin'

      - uses: actions/upload-artifact@v1
        with:
          name: daptin-darwin-10.6-amd64
          path: build/daptin-darwin-10.6-amd64
        if: github.head_ref == '' && github.repository == 'daptin/daptin'

      - uses: actions/upload-artifact@v1
        with:
          name: daptin-linux-386
          path: build/daptin-linux-386
        if: github.head_ref == '' && github.repository == 'daptin/daptin'

      - uses: actions/upload-artifact@v1
        with:
          name: daptin-linux-arm-5
          path: build/daptin-linux-arm-5
        if: github.head_ref == '' && github.repository == 'daptin/daptin'

      - uses: actions/upload-artifact@v1
        with:
          name: daptin-linux-arm-6
          path: build/daptin-linux-arm-6
        if: github.head_ref == '' && github.repository == 'daptin/daptin'

      - uses: actions/upload-artifact@v1
        with:
          name: daptin-linux-arm-7
          path: build/daptin-linux-arm-7
        if: github.head_ref == '' && github.repository == 'daptin/daptin'

      - uses: actions/upload-artifact@v1
        with:
          name: daptin-linux-mips
          path: build/daptin-linux-mips
        if: github.head_ref == '' && github.repository == 'daptin/daptin'

      - uses: actions/upload-artifact@v1
        with:
          name: daptin-linux-mipsle
          path: build/daptin-linux-mipsle
        if: github.head_ref == '' && github.repository == 'daptin/daptin'

      - uses: actions/upload-artifact@v1
        with:
          name: daptin-linux-mips64
          path: build/daptin-linux-mips64
        if: github.head_ref == '' && github.repository == 'daptin/daptin'

      - uses: actions/upload-artifact@v1
        with:
          name: daptin-linux-mips64le
          path: build/daptin-linux-mips64le
        if: github.head_ref == '' && github.repository == 'daptin/daptin'


      - uses: actions/upload-artifact@v1
        with:
          name: daptin-windows-4.0-amd64.exe
          path: build/daptin-windows-4.0-amd64.exe
        if: github.head_ref == '' && github.repository == 'daptin/daptin'


      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            ./build/daptin-linux-amd64
            ./build/daptin-darwin-10.6-amd64
            ./build/daptin-linux-386
            ./build/daptin-linux-arm-5
            ./build/daptin-linux-arm-6
            ./build/daptin-linux-arm-7
            ./build/daptin-linux-mips
            ./build/daptin-linux-mipsle
            ./build/daptin-linux-mips64
            ./build/daptin-linux-mips64le
            ./build/daptin-windows-4.0-amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

